import tkinter as tk
from tkinter import messagebox
from classes.user import User
from classes.job_class import JobClass
from classes.item import Avatar

class Register:
    def __init__(self, root):
        self.root = root
        self.create_ui()

    def create_ui(self):
        self.root.title("Register")

        tk.Label(self.root, text="Real Name:").grid(row=0, column=0, sticky="w")
        self.real_name_entry = tk.Entry(self.root)
        self.real_name_entry.grid(row=0, column=1, sticky="w")
        tk.Label(self.root, text="Age:").grid(row=1, column=0, sticky="w")
        self.age_entry = tk.Entry(self.root)
        self.age_entry.grid(row=1, column=1, sticky="w")
        tk.Label(self.root, text="Education Level:").grid(row=2, column=0, sticky="w")
        self.education_lvl_entry = tk.Entry(self.root)
        self.education_lvl_entry.grid(row=2, column=1, sticky="w")
        tk.Label(self.root, text="Email:").grid(row=3, column=0, sticky="w")
        self.email_entry = tk.Entry(self.root)
        self.email_entry.grid(row=3, column=1, sticky="w")
        tk.Label(self.root, text="Password:").grid(row=4, column=0, sticky="w")
        self.password_entry = tk.Entry(self.root, show="*")
        self.password_entry.grid(row=4, column=1, sticky="w")
        tk.Label(self.root, text="Field of Education:").grid(row=5, column=0, sticky="w")
        self.field_of_education_entry = tk.Entry(self.root)
        self.field_of_education_entry.grid(row=5, column=1, sticky="w")
        tk.Label(self.root, text="Hobbies:").grid(row=6, column=0, sticky="w")
        self.hobbies_entry = tk.Entry(self.root)
        self.hobbies_entry.grid(row=6, column=1, sticky="w")
        tk.Label(self.root, text="School Attending:").grid(row=7, column=0, sticky="w")
        self.school_attending_entry = tk.Entry(self.root)
        self.school_attending_entry.grid(row=7, column=1, sticky="w")
        tk.Label(self.root, text="Likes:").grid(row=8, column=0, sticky="w")
        self.likes_entry = tk.Entry(self.root)
        self.likes_entry.grid(row=8, column=1, sticky="w")
        tk.Label(self.root, text="Dislikes:").grid(row=9, column=0, sticky="w")
        self.dislikes_entry = tk.Entry(self.root)
        self.dislikes_entry.grid(row=9, column=1, sticky="w")
        tk.Label(self.root, text="Player Name:").grid(row=10, column=0, sticky="w")
        self.player_name_entry = tk.Entry(self.root)
        self.player_name_entry.grid(row=10, column=1, sticky="w")
        tk.Label(self.root, text="Job Class:").grid(row=11, column=0, sticky="w")
        self.job_class_entry = tk.Entry(self.root)
        self.job_class_entry.grid(row=11, column=1, sticky="w")
        tk.Label(self.root, text="Avatar Image Path:").grid(row=12, column=0, sticky="w")
        self.avatar_entry = tk.Entry(self.root)
        self.avatar_entry.grid(row=12, column=1, sticky="w")
        tk.Label(self.root, text="Strength:").grid(row=13, column=0, sticky="w")
        self.strength_entry = tk.Entry(self.root)
        self.strength_entry.grid(row=13, column=1, sticky="w")
        tk.Label(self.root, text="Agility:").grid(row=14, column=0, sticky="w")
        self.agility_entry = tk.Entry(self.root)
        self.agility_entry.grid(row=14, column=1, sticky="w")
        tk.Label(self.root, text="Stamina:").grid(row=15, column=0, sticky="w")
        self.stamina_entry = tk.Entry(self.root)
        self.stamina_entry.grid(row=15, column=1, sticky="w")
        tk.Label(self.root, text="Vitality:").grid(row=16, column=0, sticky="w")
        self.vitality_entry = tk.Entry(self.root)
        self.vitality_entry.grid(row=16, column=1, sticky="w")
        tk.Label(self.root, text="Intelligence:").grid(row=17, column=0, sticky="w")
        self.intelligence_entry = tk.Entry(self.root)
        self.intelligence_entry.grid(row=17, column=1, sticky="w")
        tk.Label(self.root, text="Level:").grid(row=18, column=0, sticky="w")
        self.lvl_entry = tk.Entry(self.root)
        self.lvl_entry.grid(row=18, column=1, sticky="w")
        tk.Label(self.root, text="Experience:").grid(row=19, column=0, sticky="w")
        self.exp_entry = tk.Entry(self.root)
        self.exp_entry.grid(row=19, column=1, sticky="w")
        tk.Button(self.root, text="Register", command=self.register).grid(row=20, column=0, columnspan=2, pady=10)

    def register(self):
        real_name = self.real_name_entry.get()
        age = self.age_entry.get()
        education_lvl = self.education_lvl_entry.get()
        email = self.email_entry.get()
        password = self.password_entry.get()
        field_of_education = self.field_of_education_entry.get()
        hobbies = self.hobbies_entry.get()
        school_attending = self.school_attending_entry.get()
        likes = self.likes_entry.get()
        dislikes = self.dislikes_entry.get()
        player_name = self.player_name_entry.get()
        job_class = JobClass(self.job_class_entry.get())
        avatar = Avatar(self.avatar_entry.get())
        strength = int(self.strength_entry.get())
        agility = int(self.agility_entry.get())
        stamina = int(self.stamina_entry.get())
        vitality = int(self.vitality_entry.get())
        intelligence = int(self.intelligence_entry.get())
        lvl = int(self.lvl_entry.get())
        exp = int(self.exp_entry.get())

        user = User(real_name, age, education_lvl, email, password, field_of_education, hobbies, school_attending, likes, dislikes, player_name, job_class, avatar, strength, agility, stamina, vitality, intelligence, lvl, exp)
        user.save()
        messagebox.showinfo("Register", "Registration successful!")
        self.root.destroy()
        root = tk.Tk()
        Login(root, lambda email: print(f"Registered and logged in as {email}"))
        root.mainloop()

if __name__ == "__main__":
    root = tk.Tk()
    register = Register(root)
    root.mainloop()
